PaySettlementService: 
    Db:
        LogsConnString:
            settings-key: PaySettlementService-LogsConnString
            types: [ AzureTableStorage, Tag ]
        DataConnString: 
            settings-key: PaySettlementService-DataConnString
            types: [ AzureTableStorage, Tag ]
        PaymentRequestsTableName: PaymentRequests
        TradeOrdersTableName: TradeOrders
        TransferToMarketQueue: TransferToMarket
        TransferToMerchantQueue: TransferToMerchant
    PaymentRequestsSubscriber:
        ConnectionString: 
            settings-key: GeneralRabbitMqConnectionString
            types: [ RabbitMq, Tag ]
        ExchangeName: 
            settings-key: PaySettlementService-PaymentRequestsSubscriber-ExchangeName
            types: [ Tag ]
        QueueName: 
            settings-key: PaySettlementService-PaymentRequestsSubscriber-QueueName
            types: [ Tag ]
    SettlementStatusPublisher:
        ConnectionString: 
            settings-key: GeneralRabbitMqConnectionString
            types: [ RabbitMq, Tag ]
        ExchangeName: 
            settings-key: PaySettlementService-SettlementStatusPublisher-ExchangeName
            types: [ Tag ]
    TradeService:
        Interval:
            settings-key: PaySettlementService-TradeService-Interval
            types: [ Tag ]
    TransferToMarketService:
        Interval:
            settings-key: PaySettlementService-TransferToMarketService-Interval
            types: [ Tag ]
        MaxTransfersPerTransaction: 
            settings-key: PaySettlementService-TransferToMarketService-MaxTransfersPerTransaction
            types: [ Tag ]
        MultisigWalletAddress:
            settings-key: PaySettlementService-TransferToMarketService-MultisigWalletAddress
            types: [ Tag ]
    AssetService:
        ExpirationPeriod:
            settings-key: PaySettlementService-AssetService-ExpirationPeriod
            types: [ Tag ]
        PaymentAssetId: 
            settings-key: PaySettlementService-AssetService-PaymentAssetId
            types: [ Tag ]
        SettlementAssetIds:
            settings-key: PaySettlementService-AssetService-SettlementAssetIds
            types: [ JsonArray, Tag ]    
    TransferToMerchantService:
        Interval:
            settings-key: PaySettlementService-TransferToMerchantService-Interval
            types: [ Tag ]
    ClientId: 
        settings-key: PaySettlementService-ClientId
        types: [ Tag ]            
    CqrsEnvironment:
        settings-key: PaySettlementService-CqrsEnvironment
        types: [ Tag ]
    IsMainNet:
        settings-key: PaySettlementService-IsMainNet
        types: [ Tag ]
        
AssetsServiceClient:  
    ServiceUrl:
        settings-key: AssetsServiceUrl
        types: [ Tag ]
    ExpirationPeriod:
        settings-key: AssetsServiceExpirationPeriod
        
BalancesServiceClient:
    ServiceUrl:
        settings-key: BalancesServiceUrl
        types: [ Tag ]
        
MatchingEngineClient:
    IpEndpoint: 
        Port: 
            settings-key: MatchingEngine-Port
            types: [ Tag ]
        Host:
            settings-key: MatchingEngine-Host
            types: [ Tag ]
            
NinjaServiceClient: 
    ServiceUrl: 
        settings-key: NinjaServiceUrl
        types: [ Tag ]
        
PayInternalServiceClient: 
    ServiceUrl: 
        settings-key: PayInternalServiceUrl
        types: [ Tag ]
        
PayMerchantServiceClient:
    ServiceUrl:
        settings-key: PayMerchantServiceUrl
        types: [Tag]
        
ExchangeOperationsServiceClient:
    ServiceUrl:
        settings-key: ExchangeOperationsServiceUrl    
        types: [ Tag ]
        
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
        
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types: [ AzureTableStorage ]
        QueueName:
            settings-key: SlackQueueName
            types: [ AzureTableStorage ]